spring.application.name=nc
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.session.jdbc.initialize-schema=always

spring.jpa.mapping-resources=\
hibernate/Brand.hbm.xml,\
hibernate/Color.hbm.xml,\
hibernate/Product.hbm.xml,\
hibernate/ProductDetail.hbm.xml,\
hibernate/Cart.hbm.xml,\
hibernate/ItemCart.hbm.xml,\
hibernate/User.hbm.xml,\
hibernate/Client.hbm.xml,\
hibernate/Checkout.hbm.xml,\
hibernate/ItemCheckout.hbm.xml,\
hibernate/CheckoutIdempotency.hbm.xml,\
hibernate/Admin.hbm.xml

server.servlet.context-path=/api/v1

cors.allowed-origins=http://localhost:5173

jwt.secret=${JWT.SECRET}

admin.password=${ADMIN.PASSWORD}

admin.email=${ADMIN.EMAIL}

server.port=${SERVER_PORT}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ADMIN.EMAIL}
spring.mail.password=${EMAIL.PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
